### ISSUE TITLE
symlinked device files seems not to resolve properly

### ISSUE THREAD

**Issue by torbjorn** [dagolden/Path-Tiny#168]
perl -MPath::Tiny -E 'say $_->realpath for path("/dev/disk/by-id")->children()'

On my Fedora 22 system all those files are symlinks. I see them nonresolved when I print them.

**Comment by torbjorn** [comment]
Cwd::realpath is never called on the filename or the full path, just the parent dir it seems.

See also irc #perl@freenode around 2016-04-11 10:20 CET for some discussion

**Comment by xdg** [comment]
Looking at the code, I see that if a symlink resolves to a path with symlinks, it won't subsequently get resolved via realpath.  I'm not sure if that's what's happening for you, though.

Could you please give me more details about the symlink structure of your paths in questions so I can replicate the issue exactly? Or, best would be if you could write a short test file that creates a symlink structure that demonstrates the problem directly.

Thanks,
David

**Comment by xdg** [comment]
Actually, looking closer, the code resolves symlinks in a loop until
the final result is not a symlink, at which point the parent path is
resolved via realpath.  

For non-symlinks, there's no difference resolving path or parent path,
except whether not non-existent paths are fatal, which differs by platform,
which is why we check parent path and not path.

I don't see how you could wind up with unresolved symlinks, so I definitely
need a minimal reproducer to make any progress on this.

**Comment by torbjorn** [comment]
$ cd ~
$ mkdir tmp
$ cd tmp
$ touch foo
$ mkdir tmp2
$ cd tmp2
$ ln -s ../foo bar
$ cd ~
$ ls -l tmp/tmp2/bar
# output: lrwxrwxrwx. 1 tl tl 6 Apr 12 10:26 tmp/tmp2/bar -> ../foo

$ perl -MPath::Tiny -E 'say path("tmp/tmp2/bar")->realpath'
# output: /home/tl/tmp/tmp2/bar (not resolved, it should have been)

$ perl -MCwd=abs_path -MPath::Tiny -E 'say abs_path path("tmp/tmp2/bar")'
# output: /home/tl/tmp/foo (Cwd resolves it, but P::T never calls Cwd::abs_path on the full path)

**Comment by torbjorn** [comment]
Better:

`#!/usr/bin/perl

use strict;
use warnings;
use Test::Most tests => 6;
use Test::Warnings;

use Path::Tiny;
use Cwd 'abs_path';

my $td = Path::Tiny->tempdir;
$td->child( qw/tmp tmp2/ )->mkpath;

my $foo = $td->child( qw/tmp foo/ )->touch;
my $bar = $td->child( qw/tmp tmp2 bar/ );

symlink $foo, $bar;

ok -f $foo, "it's a file";
ok -l $bar, "it's a link";

is readlink $bar, $foo, "the link seems right";
is abs_path($bar), $foo, "abs_path gets's it right";

note "*drumroll*";
is $bar->realpath, $foo, "realpath get's it right";
`

**Comment by xdg** [comment]
Your test file doesn't fail, but your shell code does.  It looks like it has to do with relative symlink resolution. I have a draft of a fix, but I want to get a failing (automated) test written first before I merge it.

Thanks for giving a replication!

**Comment by xdg** [comment]
Fixed in 7c89d9687facae58a4e9d658e5fb38115f28942f.  Released to CPAN as DAGOLDEN/Path-Tiny-0.087-TRIAL.tar.gz
